### ISSUE TITLE
This ND2 has no recorded start time

### ISSUE THREAD

**Issue by simone-codeluppi** [jimrybarski/nd2reader#100]
Hi
I tried to run nd2reader to convert a multiposition (xyz) file with two channels and I get a no recorded time error (I guess it is missing in the DB).
I pasted the traceback below.

Thanks a lot! this tool will really help me!

Simone

---

ValueError                                Traceback (most recent call last)
<ipython-input-23-9378dfda34e2> in <module>()
----> 1 nd2file=nd2.Nd2('/Users/simone/Desktop/test/ND2conversion/Other_ND2/Testformat.nd2')

/Users/simone/Desktop/smFISH-analysis-package/nd2reader-master/nd2reader/interface.py in **init**(self, filename)
     17         major_version, minor_version = get_version(self._fh)
     18         parser = get_parser(self._fh, major_version, minor_version)
---> 19         self._driver = parser.driver
     20         self._metadata = parser.metadata
     21 

/Users/simone/Desktop/smFISH-analysis-package/nd2reader-master/nd2reader/parser/v3.py in driver(self)
     31     @property
     32     def driver(self):
---> 33         return V3Driver(self.metadata, self._label_map, self._fh)
     34 
     35     def _parse_metadata(self):

/Users/simone/Desktop/smFISH-analysis-package/nd2reader-master/nd2reader/parser/v3.py in metadata(self)
     26     def metadata(self):
     27         if not self._metadata:
---> 28             self._parse_metadata()
     29         return self._metadata
     30 

/Users/simone/Desktop/smFISH-analysis-package/nd2reader-master/nd2reader/parser/v3.py in _parse_metadata(self)
     49         width = metadata_dict[six.b('ImageAttributes')][six.b('SLxImageAttributes')][six.b('uiWidth')]
     50         channels = self._parse_channels(metadata_dict)
---> 51         date = self._parse_date(metadata_dict)
     52         fields_of_view = self._parse_fields_of_view(metadata_dict)
     53         frames = self._parse_frames(metadata_dict)

/Users/simone/Desktop/smFISH-analysis-package/nd2reader-master/nd2reader/parser/v3.py in _parse_date(self, metadata_dict)
     79                 continue
     80             return absolute_start_12 if absolute_start_12 else absolute_start_24
---> 81         raise ValueError("This ND2 has no recorded start time. This is probably a bug.")
     82 
     83     def _parse_channels(self, metadata_dict):

ValueError: This ND2 has no recorded start time. This is probably a bug.

**Comment by jimrybarski** [comment]
I believe I've fixed this. Could you install branch `101-dont-require-date` and see if it works?

**Comment by jimrybarski** [comment]
Alternatively @simone-codeluppi if you want to send me a copy (or partial copy) of your Nd2 I'd be happy to check myself.

**Comment by simone-codeluppi** [comment]
Hi!
I managed to load the .nd2 file and get each image in numpy array. Thanks a lot to fix the issue! 
really appreciated!
Simone
