### ISSUE TITLE
opening file by attributes

### ISSUE THREAD

**Issue by EnricoGiampieri** [jimrybarski/nd2reader#106]
Hi! 
first of all, thank you very much fr writing this library, it has been years that I've hoped for someone to be able to do a pure python (without java dependencies) implementation!

I'm trying to read some test images and it work nicely, but if I try to use the get_image method of the Nd2 object, it returns this error:

```
In [25]: nd2.get_image(0, 0, 'bf', 0)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-25-66ac2986ecec> in <module>()
----> 1 nd2.get_image(0, 0, 'bf', 0)

/usr/local/lib/python3.4/dist-packages/nd2reader/interface.py in get_image(self, frame_number, field_of_view, channel_name, z_level)
    160 
    161         """
--> 162         return self._driver.get_image_by_attributes(frame_number, field_of_view, channel_name, z_level)
    163 
    164     def close(self):

AttributeError: 'V3Driver' object has no attribute 'get_image_by_attributes'
```

The attributes are correct, the image is there and can be read correctly (and has the corresponding metadata), but appears that the relative method has not been implemented.

I'm using the 1.1.3 version (the one that pip install) on python 3.4

**Comment by jimrybarski** [comment]
Thanks for the bug report! I've implemented the missing method, which is now available in version 1.1.4. Please let me know if anything still doesn't work.

**Comment by EnricoGiampieri** [comment]
fastest delivery ever :)
Thank you very much, I plan to use the library intensively in the next few monts, I'll let you know if I find anything and if possible I'll cooperate with some code.
Speaking of which, do you get the metadata from the XML in the file? or do you parse them in a different way?

**Comment by jimrybarski** [comment]
The metadata does contain a small amount of XML (which we don't currently parse) and a large block of binary data which contains everything that's currently available. I'm not sure why it is the way it is, presumably it's just a C# dictionary that's been serialized. You can check out `parser/v3.py` for the gory details if you're interested.

The XML might actually have something worth getting, in fact I suspect the actual z-axis offsets are stored there (currently we can order images from low to high but NIS Elements is able to tell you the exact distances in micrometers, so it must be in there somewhere).

**Comment by EnricoGiampieri** [comment]
I was checking out, and there is information about the z position in the xml, but I don't have any image available with multiples z values, so I'm not sure if more information would be available. I will try in the next few days with some ad-hoc image and I'll see if I can scrape some useful info out of it. Each file have several xml pieces, and in my images each one is contained in a <variant> tag, this is the best indicator I've found at the moment...
