### ISSUE TITLE
Parse XML metadata

### ISSUE THREAD

**Issue by jimrybarski** [jimrybarski/nd2reader#117]
The metadata is mostly binary but also contains some XML regions.
- [x] Determine locations of XML in memory-efficient way 
- [x] Decide what data in the XML is worth extracting
- [x] Choose an XML-parsing library
- [x] Extract the data

**Comment by jimrybarski** [comment]
Actually I'm beginning to doubt whether we should do this. Much of the information is already in the binary data that we capture. If we can find anything in the XML that's unique or if Version 2 files only have that info in their XML, we'll continue with this, otherwise, we should probably not even bother.

**Comment by EnricoGiampieri** [comment]
From what I've seen the XML contains details about the microscope setting rather than specifics about the images (aside from the size). I would just scrap them and return as an XML tree. They could be interesting to keep track of what exactly happened in the experiment (especially if some information has been lost to time, like the precise exposure time or the image binning), but I don't think they are worth analysing aside from that.

**Comment by jimrybarski** [comment]
I think for version 3 files (those made by NIS Elements 4.x) the info in the XML is redundant. However, version 2 files don't have any binary metadata and it's all in the XML, so either way we definitely need to parse it. It would be interesting to see if it's really redundant or if there are any extra goodies. Unfortunately the Z-axis offsets are not in the XML but I did find out where they are, though I can't understand what the values mean.

I'm going to refactor a little bit to expose this data so we can compare (see #123). Strangely, the label map (a part at the end of the file that gives the addresses of each section) does not give the locations of the XML, but there is a section immediately following each XML segment so you could take that number and just parse everything behind it.

**Comment by jimrybarski** [comment]
@EnricoGiampieri I've refactored a bit so you can now see what's in the binary metadata. This script will dump the entire dict, which is quite large. We should both try to see if version 3 files have anything in the XML that's not in there:

```
from pprint import pprint
from nd2reader.parser.v3 import V3Parser


with open("my_data.nd2", "rb") as fh:
    p = V3Parser(fh)
    metadata = p._build_metadata_dict()
    pprint(metadata)
```

**Comment by jimrybarski** [comment]
I looked through the XML but found nothing of interest (to me, anyway!). The XML is now automatically parsed into an `OrderedDict` and can be accessed like so:

```
from nd2reader import Nd2
nd2 = Nd2("/path/to/my.nd2")
print(nd2._parser.raw_metadata.lut_data)
print(nd2._parser.raw_metadata.grabber_settings)
print(nd2._parser.raw_metadata.custom_data)
print(nd2._parser.raw_metadata.app_info)
```

Those four attributes are the only ones available in the Nd2s that I have. The `raw_metadata` object has other non-XML things that aren't currently exposed to users, but I'm not sure how to interpret them all. I'm going to close this issue but please open up another one if you see some information you need.
