### ISSUE TITLE
select() doesn't output the 'selected' images

### ISSUE THREAD

**Issue by simone-codeluppi** [jimrybarski/nd2reader#138]
Hi
I have been trying to use select() to speed up the selection of images of a specific channel and field of view but I cannot get it to work. When I read the nd2 file the attributes (channel, field of view and z_level) for each of the images are present and correct. However when I try to use the select method I am not able to get anything out. I attached a link to the image if it is helpful.

https://ki.box.com/s/horocvw7bzng1344vcdr8auc4ofiwo2s
## Image infos:

Image size: 2048x2048 (HxW)
Frames: 1
Channels: Cy3Narrow, DAPI, FITC, TxRed-modified
Fields of View: 5
Z-Levels: 35

Thanks a lot
Simone

**Comment by jimrybarski** [comment]
OK, I see the problem. Basically, I assumed everyone would have the same use case as me :)

I've pushed a potential fix for this to the branch `138-bug-select`, which you can try out in the meantime. It seems to work for me but I want to give it a think and write some tests before I merge it into `master`.

**Comment by simone-codeluppi** [comment]
Thanks a lot for the help! I tested it on another couple of files and the `select()` function works nicely. I will run a batch process later on during the week on a big number of files and I will keep you posted on how it will go.

**Comment by jimrybarski** [comment]
That's good to hear. This fix actually surfaced a bug that makes some files unreadable, which I need to resolve before merging, but I don't think it will affect you.
