### ISSUE TITLE
Cant view the raw data/array of nd2 file

### ISSUE THREAD

**Issue by the0dead0cat** [jimrybarski/nd2reader#139]
Hi,

For some reason I can't access values in the nd2 file. For example, the following code:

```
import nd2reader
nd2 = nd2reader.Nd2('/filepath/filename.nd2')
image = nd2[0]
image
```

only gives me the following instead of an array of values:

```
<ND2 Image>
2048x2048 (HxW)
Timestamp: 3.66982981682
Field of View: 0
Channel: GFP
Z-Level: 0
```

Have you come across this before or am I doing something heinously wrong?

Thanks! :)

**Comment by jimrybarski** [comment]
You must have somehow gotten an old version of nd2reader. In that version, the actual image data is in the `data` attribute (so in your example you would need to use `image.data` or `nd2[0].data`), though I would recommend upgrading to the latest version if possible.
