### ISSUE TITLE
Select wrong channels

### ISSUE THREAD

**Issue by simone-codeluppi** [jimrybarski/nd2reader#145]
Hi
sorry...me again! 
I run the `select()` command on the image linked in the previous issue I submitted and on a few more. When I looked at the numpy arrays not all  the selected images correspond to the expected channel. I don't think is a problem of the `select()` function but more of the order of the channels in the loaded metadata.

**Example**
`ImgRef=nd2.Nd2(ImgLoc)`
`ImgRef.channel`
The list I obtain is `['Cy3Narrow', 'DAPI', 'FITC', 'TxRed-modified']` (I guess alphabetical order) however the acquisition order in the `.nd2` is `['Cy3Narrow', 'TxRed-modified', 'FITC', 'DAPI']`. When I look at the imported numpy arrays:
-Cy3Narrow is correct
-DAPI channel and the TxRed-modified are inverted.
-FITC is correct
When I look at the images in the ImgRef (ex. `ImgRef[10]`) I can see that are organized according to the acquisition order in the .nd2 file and that is why I think that is a issue related on how the metadata are imported.
Thanks a lot for the help.

**Comment by jimrybarski** [comment]
I fixed this just recently, upgrading to the latest version (2.0.2) should get it to work. Let me know how that goes.

**Comment by simone-codeluppi** [comment]
Great! I version 2.0.2 on few images and works fine.
Thanks a lot!
