### ISSUE TITLE
Selecting by timepoint?

### ISSUE THREAD

**Issue by tlnagy** [jimrybarski/nd2reader#154]
Is there a way to get all images that belong to one timepoint? `select()` doesn't have a keyword argument for `frames=`.

**Comment by jimrybarski** [comment]
Yes, you can use the `start` and `stop` keywords to give it a range of frames. For a single frame number `n` you could do something like `.select(start=n, stop=n+1)`.

**Comment by tlnagy** [comment]
I thought start and stop only gave you a single image? Is there any way of getting all FOVs corresponding to single timepoint? For example, I have the following ND2 file:

```
<ND2 /path/to/file.nd2>
Created: 2016-03-17 11:04:05
Image size: 1080x1280 (HxW)
Frames: 25
Channels: DIA.ILL
Fields of View: 102
Z-Levels: 1
```

which has 25 timepoints with 102 FOV per timepoint. How can I get the FOVs corresponding to the first timepoint, second, and so on?

**Comment by tlnagy** [comment]
I know I can do something like this:

``` .python
timepoint = 3
fov_at_tp = []
for image in nd2:
    if image.frame_number == timepoint:
        fov_at_tp.append(image)
len(fov_at_tp)
```

but this is pretty inefficient as mentioned in the `select()` documentation

**Comment by jimrybarski** [comment]
`start` and `stop` should give you an iterator of all the images that fall between the range. For example, `nd2.select(start=3, stop=4)` should give you an iterator that produces 102 images, all from timepoint 3. Does that not work?

**Comment by tlnagy** [comment]
This doesn't seem to work for me:

```
len(list(nd2.select(start=3, stop=4)))
```

gives me 1, not 102 as I expect based on iterating and checking manually

**Comment by jimrybarski** [comment]
Sorry to drop things mid-issue, but I'm no longer supporting this library. See the readme for details.
