### ISSUE TITLE
Z-level information not reported correctly

### ISSUE THREAD

**Issue by shrawmag** [jimrybarski/nd2reader#157]
Dear developers,
I would like to parse my nd2 file based on the channel information and z-level information. However, only the channel information is reported correctly when I read the file. Z-Levels always shows "1". I use NIS Elements Advanced Research v 4.13 for data collection. Also, when I collect images on multiple adjacent tiles in one single experiment, the fields of View always shows "1" regardless of how many tiles are present in the nd2 file. 

Thanks,
Shrawan
Postdoc
California Institute of Technology

**Comment by jimrybarski** [comment]
Are you taking one-off images? If they're not collected in a cycle I would expect this behavior. Unfortunately, I'm closing this issue as I'm no longer supporting the library. See the readme for details.
