### ISSUE TITLE
Problem reading file

### ISSUE THREAD

**Issue by p2jones** [jimrybarski/nd2reader#61]
I've tried opening .nd2 files as follows:

``` python
import nd2reader
img = nd2reader.Nd2('01.nd2')
```

The file 01.nd2 is in the current working directory.

I receive the following error from line 47 of nd2reader/parser.py:

`<repr(<nd2reader.Nd2 at 0xf3ff4f0>) failed: KeyError: 'ImageTextInfo'>`

I edited the parser to give it a fake date, and then it got stuck on another piece of the metadata. It seems that the metadata remains empty (value of {}).

I've tried this with several files. I'm on Windows XP with python 2.7. All files were created with NIS Elements 3.10.

**Comment by jimrybarski** [comment]
It looks like `nd2reader` is only compatible with NIS Elements 4.0+. Sorry that wasn't documented anywhere. If you'd be willing to put your nd2 somewhere that I can download it, I'd love to see if it would be feasible to add support for files produced by version 3.x.

**Comment by p2jones** [comment]
Thanks, it would be great if that were possible. Here's a file: https://www.dropbox.com/s/c8wroiiaobomh2c/example.nd2?dl=0

**Comment by jimrybarski** [comment]
Thanks! After looking at it briefly, the way they structure these files is significantly simpler than in version 4.x so I think this will be completely doable. I'll keep you updated, though you might have to use Bioformats in the meantime.

**Comment by p2jones** [comment]
Ok, thanks again. I'll watch out for updates.

**Comment by jimrybarski** [comment]
I'm closing this even though it's unresolved, I just don't think I'll be able to commit the time to working on this. I'm leaving #67 open in case someone else wants to add V3 support. As an alternative you could try [pims](https://github.com/soft-matter/pims_nd2) which uses the SDK that Nikon produces.
