### ISSUE TITLE
Write driver for NIS Elements 3.x files

### ISSUE THREAD

**Issue by jimrybarski** [jimrybarski/nd2reader#67]
We currently have a file from NIS Elements 3.10 which we'll use as the test case. The metadata is stored as XML though we need to figure out where the pointers to the metadata are, and also how to determine the boundaries of the images. We also need to determine if images are stored in the same way (interleaved by channel)

Related: #61 #66

**Comment by jimrybarski** [comment]
@delao27 would you be interested in trying to figure out how to parse these files?

**Comment by p2jones** [comment]
Perhaps this is helpful? From this page: https://www.openmicroscopy.org/site/support/bio-formats5.1/formats/nikon-nis-elements-nd2.html

"There are two distinct versions of ND2: an old version, which uses JPEG-2000 compression, and a new version which is either uncompressed or Zip-compressed. We are not aware of the version number or release date for either format."

**Comment by EnricoGiampieri** [comment]
I tried to write this code to extract the xml metadata. I have nly access to the data prepared in my laboratory, so I'm not sure if I'm losing something, I'm digging the the raw data to try to understand what it's going on. In each file there are several metadata groups, each one with a different set of information, but they don't seems to be information about the images, as about the experimental procedures.

This code is just an hack, but maybe can be a starting point?

```
def read_metadata(filename):
    pattern = re.compile(b"<variant version=\"1\.0\">(.+?)<\/variant>")
    with open(filename, 'rb') as file:
        data = file.read()
        results = pattern.findall(data)
    results = [r.decode('utf8') for r in results]
    results = [r.replace('><', '>\n<') for r in results]
    return results

def parse_xml(string, sep='    '):
    from lxml import etree
    import xml.dom.minidom
    root = etree.fromstring(string)
    nicexml = etree.tostring(root, pretty_print=True, encoding='utf8').decode('utf8')
    xml_struct = xml.dom.minidom.parseString(nicexml)
    uglyXml = xml_struct.toprettyxml(indent=sep, newl='\n')
    for i in range(1, 10):
        uglyXml = uglyXml.replace('\n'+sep*i+'\n', '\n\n')
    uglyXml= uglyXml.replace('\n\n', '\n')
    uglyXml= uglyXml.replace('\n\n', '\n')
    return uglyXml
```

**Comment by jimrybarski** [comment]
@EnricoGiampieri I made an issue for XML parsing at #117. Since both 3.x and 4.x files have XML I think this should be its own issue.

**Comment by jimrybarski** [comment]
@p2jones we haven't forgotten about this, it's just taking some time. Sorry for the wait.
